apiVersion: v1
kind: Pod
metadata:
  name: mym-discovery-server
  labels:
    app: mym-discovery-server
spec:
  containers:
  - name: mym-discovery-server
    image: rkumar0206/mym-discovery-server:v1.0.1
    env:
      - name: config.server.host
        value: service-mym-config
      - name: config.server.port
        value: "8727"
    ports:
      - containerPort: 8845
        name: discovery-port
---
apiVersion: v1
kind: Service
metadata:
  name: service-mym-discovery-server
spec:
  type: NodePort
  selector:
    app: mym-discovery-server
  ports:
    - protocol: TCP
      port: 8845
      targetPort: discovery-port
      nodePort: 30200